<a href="https://colab.research.google.com/github/aniketpathak028/learn-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [3]:
! nvidia-smi # to check gpu config

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

tensors created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

8

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([9, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape # shape is the count of elements in each dimension

torch.Size([1, 3, 3])

In [17]:
print(TENSOR.size()) # alias for shape

torch.Size([1, 3, 3])


In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0][1]

tensor([3, 6, 9])

In [20]:
TENSOR2 = torch.tensor([[[0, 1, 8], [1, 3, 4], [4, 5, 6], [3, 2, 1]],
           [[2, 1, 3], [5, 1, 9], [0, 5, 6], [5, 2, 1]],
           [[5, 1, 4], [5, 4, 9], [0, 9, 6], [1, 2, 8]]])

In [21]:
TENSOR2.ndim

3

### Note:
##### usually scalars and vectors are represented in lower case and matrix and tensors are represented in upper case

In [22]:
TENSOR2.shape

torch.Size([3, 4, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ```

In [23]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1322, 0.0271, 0.9082, 0.3333],
        [0.1150, 0.4749, 0.8185, 0.6048],
        [0.1849, 0.6633, 0.0824, 0.3167]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor1= torch.rand(10, 10, 10)
random_tensor1

tensor([[[1.7619e-01, 2.4851e-01, 3.8596e-01, 8.4088e-01, 9.5955e-01,
          2.2270e-01, 7.4175e-01, 5.7654e-01, 5.2462e-02, 3.7635e-01],
         [2.3726e-01, 5.7748e-01, 1.3610e-01, 7.0979e-01, 1.4486e-01,
          9.3689e-01, 4.1728e-01, 5.1286e-01, 3.6644e-01, 2.5263e-01],
         [2.0201e-01, 2.3628e-01, 9.0517e-01, 1.4699e-01, 3.1849e-01,
          9.8549e-01, 8.7651e-01, 1.1376e-01, 1.3097e-01, 3.1785e-02],
         [8.7528e-01, 5.1327e-02, 7.5183e-01, 3.2911e-01, 5.1426e-01,
          1.9060e-01, 2.9039e-01, 2.4512e-01, 1.2334e-01, 8.5823e-01],
         [1.1400e-01, 4.1582e-01, 6.2900e-01, 9.6114e-01, 6.1694e-01,
          7.8225e-01, 7.0135e-01, 7.7663e-01, 6.2350e-01, 2.9675e-01],
         [3.7926e-01, 3.5867e-01, 2.7322e-01, 1.6895e-01, 3.4827e-01,
          1.5007e-01, 1.1683e-01, 2.4506e-01, 4.4600e-01, 7.8484e-01],
         [4.6573e-01, 5.6215e-01, 9.3678e-02, 6.8869e-01, 1.0153e-01,
          1.4701e-01, 2.5890e-02, 2.6655e-01, 3.3792e-01, 5.8519e-02],
         [5.8

In [26]:
random_tensor1.size()

torch.Size([10, 10, 10])

In [27]:
random_tensor1.ndim

3

In [28]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [29]:
# 2 ways to create tensors are
way1= torch.rand(5,10)
way1

tensor([[0.5965, 0.9262, 0.8331, 0.1696, 0.1139, 0.2329, 0.7553, 0.2987, 0.7158,
         0.1476],
        [0.8563, 0.9332, 0.4037, 0.1551, 0.7072, 0.6188, 0.7754, 0.5886, 0.3478,
         0.5966],
        [0.4263, 0.3103, 0.0651, 0.1298, 0.6668, 0.0314, 0.1594, 0.5261, 0.7149,
         0.2472],
        [0.2911, 0.8023, 0.3504, 0.4758, 0.9235, 0.3501, 0.6519, 0.8226, 0.2038,
         0.1007],
        [0.5850, 0.7833, 0.0489, 0.3994, 0.1885, 0.0729, 0.5429, 0.2911, 0.9037,
         0.0100]])

In [30]:
way2= torch.rand(size=(5,10))
way2

tensor([[0.8007, 0.6072, 0.4908, 0.1473, 0.8980, 0.4154, 0.4649, 0.9853, 0.6304,
         0.2078],
        [0.2837, 0.9798, 0.9244, 0.4767, 0.3555, 0.4060, 0.2758, 0.0648, 0.5674,
         0.7572],
        [0.1458, 0.4048, 0.3315, 0.3331, 0.8438, 0.9448, 0.1407, 0.0760, 0.3757,
         0.8802],
        [0.5700, 0.0408, 0.7788, 0.9315, 0.9427, 0.3381, 0.0498, 0.2056, 0.3505,
         0.3590],
        [0.0368, 0.7654, 0.9172, 0.2041, 0.2881, 0.9662, 0.7136, 0.9908, 0.5518,
         0.4669]])

### Zeros and Ones

In [31]:
# create a tensor of all zeros

zeros= torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# create a tensor of all ones

ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors-like

In [34]:
# use torch.range() --> deprecated, so use arange

one2ten= torch.arange(1,11, step=2)
one2ten

tensor([1, 3, 5, 7, 9])

In [35]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & deep learning:

- Tensors not right datatype
- Tensors not right shape
- Tensors not on the right device

In [36]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what dtype is the tensor? eg. float32, float16, float64, complex32, complex64
                               device=None, # by default - cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
# convert dtype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)