<a href="https://colab.research.google.com/github/aniketpathak028/learn-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing pytorch, numpy, pandas, and matplotlib

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [2]:
! nvidia-smi # to check gpu config

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

tensors created using torch.Tensor(), read https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

8

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([9, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # shape is the count of elements in each dimension

torch.Size([1, 3, 3])

In [16]:
print(TENSOR.size()) # alias for shape

torch.Size([1, 3, 3])


In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
TENSOR[0][1]

tensor([3, 6, 9])

In [19]:
TENSOR2 = torch.tensor([[[0, 1, 8], [1, 3, 4], [4, 5, 6], [3, 2, 1]],
           [[2, 1, 3], [5, 1, 9], [0, 5, 6], [5, 2, 1]],
           [[5, 1, 4], [5, 4, 9], [0, 9, 6], [1, 2, 8]]])

In [20]:
TENSOR2.ndim

3

### Note:
##### usually scalars and vectors are represented in lower case and matrix and tensors are represented in upper case

In [21]:
TENSOR2.shape

torch.Size([3, 4, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ```

In [22]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1540, 0.8830, 0.1892, 0.1850],
        [0.1802, 0.7290, 0.0806, 0.2829],
        [0.8029, 0.2745, 0.6741, 0.3534]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor1= torch.rand(10, 10, 10)
random_tensor1

tensor([[[0.3986, 0.9505, 0.8386, 0.6950, 0.9978, 0.9531, 0.1075, 0.1849,
          0.9109, 0.5795],
         [0.9015, 0.3858, 0.1121, 0.2213, 0.4804, 0.3829, 0.1597, 0.8327,
          0.3557, 0.8716],
         [0.7347, 0.8441, 0.9679, 0.3308, 0.9275, 0.1106, 0.4259, 0.2857,
          0.7819, 0.1436],
         [0.3845, 0.4505, 0.5706, 0.4662, 0.1118, 0.3579, 0.2115, 0.6953,
          0.1218, 0.1200],
         [0.6105, 0.6581, 0.2022, 0.9749, 0.6937, 0.0569, 0.6591, 0.2165,
          0.6540, 0.0430],
         [0.8203, 0.6185, 0.2645, 0.7025, 0.1701, 0.6044, 0.2876, 0.2126,
          0.8467, 0.0281],
         [0.0737, 0.8373, 0.7697, 0.4864, 0.9405, 0.8809, 0.0449, 0.9449,
          0.5320, 0.6968],
         [0.5133, 0.3791, 0.4764, 0.8841, 0.0971, 0.9988, 0.5233, 0.9998,
          0.6696, 0.7978],
         [0.0644, 0.1520, 0.6423, 0.1569, 0.7028, 0.6425, 0.3341, 0.5814,
          0.7515, 0.9755],
         [0.8572, 0.2613, 0.6778, 0.9166, 0.8848, 0.2881, 0.9833, 0.9778,
          0.2247,

In [25]:
random_tensor1.size()

torch.Size([10, 10, 10])

In [26]:
random_tensor1.ndim

3

In [27]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [28]:
# 2 ways to create tensors are
way1= torch.rand(5,10)
way1

tensor([[0.6565, 0.2839, 0.1322, 0.3753, 0.2996, 0.1520, 0.7942, 0.8668, 0.4611,
         0.5545],
        [0.8256, 0.5443, 0.4164, 0.2809, 0.9968, 0.5981, 0.3254, 0.9330, 0.3180,
         0.2273],
        [0.4191, 0.9779, 0.4255, 0.7452, 0.7770, 0.8551, 0.5805, 0.2711, 0.9331,
         0.2949],
        [0.4317, 0.1810, 0.7601, 0.5881, 0.7057, 0.4741, 0.2459, 0.6797, 0.5544,
         0.1125],
        [0.7130, 0.4245, 0.7770, 0.1454, 0.8134, 0.6195, 0.9844, 0.9618, 0.3450,
         0.8138]])

In [29]:
way2= torch.rand(size=(5,10))
way2

tensor([[0.4871, 0.7210, 0.2522, 0.8737, 0.4965, 0.6726, 0.4094, 0.8397, 0.8413,
         0.6285],
        [0.4658, 0.1747, 0.4345, 0.7444, 0.5638, 0.2511, 0.7754, 0.3144, 0.4507,
         0.5750],
        [0.5825, 0.8565, 0.5692, 0.0213, 0.6061, 0.5796, 0.9929, 0.1095, 0.4545,
         0.7505],
        [0.9505, 0.2975, 0.6948, 0.5564, 0.3543, 0.6928, 0.5455, 0.4789, 0.7114,
         0.3444],
        [0.1479, 0.3601, 0.2585, 0.5346, 0.9795, 0.8062, 0.5227, 0.7347, 0.6776,
         0.5931]])

### Zeros and Ones

In [30]:
# create a tensor of all zeros

zeros= torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
# create a tensor of all ones

ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors-like

In [33]:
# use torch.range() --> deprecated, so use arange

one2ten= torch.arange(1,11, step=2)
one2ten

tensor([1, 3, 5, 7, 9])

In [34]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one2ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & deep learning:

- Tensors not right datatype
- Tensors not right shape
- Tensors not on the right device

In [35]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # by default - float32, possible - float16, float64, complex32, complex64
                               device=None, # by default - cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
# convert dtype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [38]:
float_16_tensor * float_32_tensor # it works sometimes, but to be aware that sometimes it can cause errors!

tensor([ 9., 36., 81.])

### Getting information from Tensors (attributes)


- Tensors not right datatype - to do get datatype, use `tensor.dtype`
- Tensors not right shape - to get shape, use `tensor.shape`
- Tensors not on the right device - to get device, use `tensor.device`

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4833, 0.0678, 0.9068, 0.9526],
        [0.4348, 0.9700, 0.7104, 0.3233],
        [0.2630, 0.8543, 0.3244, 0.2508]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

Tensor operation include:-

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplicatio

In [40]:
# addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [42]:
# substraction
tensor - 10

tensor([-9, -8, -7])

In [43]:
# division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [44]:
# built in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

2 main ways of performing multiplication in neural networks and deep learning:

- Element wise multiplication
- Matrix Multiplication (dot product)

In [46]:
# element wise

print(tensor * tensor)

tensor([1, 4, 9])


In [47]:
# matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [49]:
# using for loop
%%time
value= 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 978 µs, sys: 902 µs, total: 1.88 ms
Wall time: 1.78 ms


In [51]:
# using pytorch
%%time
torch.matmul(tensor, tensor)

CPU times: user 289 µs, sys: 24 µs, total: 313 µs
Wall time: 296 µs


tensor(14)

### The main two rules for matrix multiplication to remember are:

  The inner dimensions must match:

  `(3, 2) @ (3, 2) won't work`

  `(2, 3) @ (3, 2) will work`

  `(3, 2) @ (2, 3) will work`

  The resulting matrix has the shape of the outer dimensions:

  `(2, 3) @ (3, 2) -> (2, 2)`

  `(3, 2) @ (2, 3) -> (3, 3)`

  "@" in Python is the symbol for matrix multiplication.
