<a href="https://colab.research.google.com/github/aniketpathak028/learn-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [ ]:
! nvidia-smi # to check gpu config

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

8

In [ ]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([9, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape # shape is the count of elements in each dimention

torch.Size([1, 3, 3])

In [ ]:
print(TENSOR.size()) # alias for shape

torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

In [ ]:
TENSOR2 = torch.tensor([[[0, 1, 8], [1, 3, 4], [4, 5, 6], [3, 2, 1]],
           [[2, 1, 3], [5, 1, 9], [0, 5, 6], [5, 2, 1]],
           [[5, 1, 4], [5, 4, 9], [0, 9, 6], [1, 2, 8]]])

In [ ]:
TENSOR2.ndim

3

### Note:
##### usually scalars and vectors are represented in lower case and matrix and tensors are represented in upper case

In [ ]:
TENSOR2.shape

torch.Size([3, 4, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ```

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3693, 0.1784, 0.1267, 0.8839],
        [0.3565, 0.3586, 0.0345, 0.6948],
        [0.0671, 0.9599, 0.4056, 0.7927]])

In [ ]:
random_tensor.ndim

2