<a href="https://colab.research.google.com/github/aniketpathak028/learn-pytorch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [3]:
! nvidia-smi # to check gpu config

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

### Creating tensors

tensors created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int
scalar.item()

8

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([9, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape # shape is the count of elements in each dimention

torch.Size([1, 3, 3])

In [17]:
print(TENSOR.size()) # alias for shape

torch.Size([1, 3, 3])


In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR[0][1]

tensor([3, 6, 9])

In [20]:
TENSOR2 = torch.tensor([[[0, 1, 8], [1, 3, 4], [4, 5, 6], [3, 2, 1]],
           [[2, 1, 3], [5, 1, 9], [0, 5, 6], [5, 2, 1]],
           [[5, 1, 4], [5, 4, 9], [0, 9, 6], [1, 2, 8]]])

In [21]:
TENSOR2.ndim

3

### Note:
##### usually scalars and vectors are represented in lower case and matrix and tensors are represented in upper case

In [22]:
TENSOR2.shape

torch.Size([3, 4, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

``` start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers ```

In [23]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2338, 0.3594, 0.7914, 0.4280],
        [0.9675, 0.9479, 0.5638, 0.4924],
        [0.5771, 0.5561, 0.4521, 0.2307]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor1= torch.rand(10, 10, 10)
random_tensor1

tensor([[[9.2951e-01, 1.6100e-01, 7.9524e-01, 7.2021e-01, 8.5097e-01,
          7.2453e-01, 4.2215e-01, 3.8382e-01, 4.4708e-02, 9.8922e-01],
         [4.0121e-01, 8.7117e-01, 5.9975e-01, 5.7760e-01, 7.3492e-01,
          5.1293e-01, 3.4154e-01, 2.6319e-01, 9.8436e-01, 7.8950e-01],
         [6.3378e-01, 2.4221e-02, 7.0648e-01, 6.1907e-02, 7.3938e-01,
          3.4712e-01, 8.1231e-01, 2.7378e-01, 3.8805e-02, 1.1581e-01],
         [8.1213e-01, 3.4334e-01, 8.4349e-01, 8.9488e-01, 1.7300e-02,
          8.5124e-01, 2.6171e-01, 4.5296e-01, 6.7391e-02, 9.1391e-01],
         [4.8567e-01, 7.7245e-01, 4.8687e-01, 6.6850e-01, 3.0598e-01,
          2.7854e-02, 9.0796e-01, 7.6909e-02, 6.3054e-02, 6.8582e-01],
         [2.7818e-01, 8.3034e-01, 9.5336e-01, 2.2036e-01, 7.8919e-01,
          5.3810e-01, 6.9914e-01, 9.6194e-01, 9.7611e-01, 5.5633e-02],
         [7.5869e-01, 4.5619e-01, 9.1405e-01, 5.2611e-01, 5.4119e-01,
          1.5751e-02, 8.2865e-01, 7.8974e-01, 6.5388e-01, 1.7802e-01],
         [8.6

In [26]:
random_tensor1.size()

torch.Size([10, 10, 10])

In [27]:
random_tensor1.ndim

3

In [28]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [29]:
# 2 ways to create tensors are
way1= torch.rand(5,10)
way1

tensor([[0.4828, 0.0205, 0.5092, 0.5468, 0.3503, 0.9404, 0.5388, 0.7964, 0.1241,
         0.6168],
        [0.2632, 0.1180, 0.3329, 0.5433, 0.1626, 0.1329, 0.8979, 0.9222, 0.8999,
         0.9173],
        [0.6728, 0.6482, 0.7112, 0.2917, 0.6927, 0.0211, 0.8329, 0.2198, 0.8342,
         0.4283],
        [0.3166, 0.2960, 0.0380, 0.3249, 0.0908, 0.9040, 0.5684, 0.0142, 0.2960,
         0.3574],
        [0.9946, 0.6769, 0.2829, 0.0067, 0.2444, 0.0909, 0.8083, 0.1323, 0.6290,
         0.3955]])

In [30]:
way2= torch.rand(size=(5,10))
way2

tensor([[0.7502, 0.2531, 0.2224, 0.8587, 0.6657, 0.6294, 0.1819, 0.5206, 0.1174,
         0.8721],
        [0.4373, 0.3041, 0.4966, 0.0247, 0.6852, 0.9031, 0.3930, 0.7507, 0.3752,
         0.8598],
        [0.2249, 0.3938, 0.2033, 0.3732, 0.3564, 0.7642, 0.8934, 0.3359, 0.9480,
         0.3413],
        [0.7076, 0.6075, 0.3137, 0.0376, 0.5522, 0.3250, 0.1077, 0.6575, 0.3910,
         0.2051],
        [0.5989, 0.7081, 0.6320, 0.0583, 0.8307, 0.8841, 0.6964, 0.4563, 0.3744,
         0.4799]])

## Zeros and Ones

In [31]:
# create a tensor of all zeros

zeros= torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# create a tensor of all ones

ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32